actions:
  actionDefs:
    install:
      metadata:
        name: "install"
        description: "Installs Palantir for Cloudpak for Data"
        case.launcher.type: "script"
        case.launcher.isdefault: "true"
      requires:
        and:
        - "/case/prereqs/k8sDistros/openshift"
        - "/case/prereqs/k8sResources/workerIntelLinux"
        - "/case/prereqs/client/oc"
      roles: []
      k8sPermissions:
        rules:
        - rule:
            group: "*"
            resource: "*"
            verbs: ["*"]
            version: "*"
