kind: ConfigMap
apiVersion: v1
metadata:
  labels:
    app.kubernetes.io/name: palantir-operator
    app.kubernetes.io/managed-by: palantir.com
    app.kubernetes.io/instance: palantir-operator
  name: palantir-operator-user-config
data:
  userconfig.yml: |
    artifactory-creds:
      src-secret: palantir-ext-creds
      dst-secret: palantir-ext-creds
    cpd-namespace: #CPD_NAMESPACE#
    cpd-domain: #CPD_DOMAIN#
    disable-firewalls: #DISABLE_NETWORK_FIREWALLS#
    data-storage:
      path: #DATA_STORAGE_PATH#
      endpoint: #DATA_STORAGE_ENDPOINT#
      creds-secret: data-storage-creds
      encryption-secret: data-storage-encryption
    frontdoor-config:
      domain: palantir-cloudpak.#CPD_DOMAIN#
      cert-secret:  proxy-certificate
    image-registry-prefix: docker.external.palantir.build
    namespace-prefix: palantir-cloudpak
    registration-config-secret: registration-info
    storage-class: #STORAGE_CLASS#
