kind: ConfigMap
apiVersion: v1
metadata:
  labels:
    app.kubernetes.io/name: palantir-operator
    app.kubernetes.io/managed-by: palantir.com
    app.kubernetes.io/instance: palantir-operator
  name: palantir-operator
data:
  install.yml: |
    use-console-log: true
    on-prem: true
    server:
      address: 0.0.0.0
      port: 3756
      context-path: /palantir-operator
    cluster-config:
      disable-firewalls: {{ .disableFirewalls }}
      registration-config-secret: registration-info
      data-storage:
        path: {{ .dataStoragePath }}
        endpoint: {{ .dataStorageEndpoint }}
        creds-secret: data-storage-creds
        encryption-secret: data-storage-encryption
      artifactory-creds:
        src-secret: docker-pull-{{ .palantirOperatorNamespace }}-docker-external-palantir-build-base-registry-registry
        dst-secret: palantir-ext-creds
      own-namespace-env-var: OPERATOR_NAMESPACE
      instance-name: {{ .instanceName }}
      frontdoor-config:
        base-domain: {{ .cp4dFQDN }}
        base-64-cert: {{ .proxyCertificateBase64 }}
        base-64-key: {{ .proxyPrivateKeyBase64 }}
      envoy-service-spec:
        ports:
        - port: 6443
          name: envoy
          protocol: TCP
        selector:
          rubix-app: envoy
      image-registry-prefix: {{ .imageRegistryPrefix }}
      cpd-namespace: {{ .cpdNamespace }}
      storage-class: {{ .storageClass }}
      application-class: small
  runtime.yml: |
    logging:
      level: info
